import LocalizedStrings from 'react-localization';

 let strings = new LocalizedStrings({
 en:{
     specification: "specialisation",
     idCage: "idCage",

     monday: "Mo",
     tuesday: "Tu",
     wednesday: "We",
     thursday: "Th",
     friday: "Fr",
     saturday: "Sa",
     sunday: "Su",
     _id: 'id',
     contains: 'contains',
     add: 'Add',
     select: 'Select',
     normal: 'Normal',
     deleteSelected: 'Delete selected',
     unselect: 'Unselect',
     registered: 'registered',
     name: 'name',
     location: 'location',
     animalKind: 'animalKind',

     capacity: 'capacity',
     idFarm: 'idFarm',


     locale: 'en-US',
     previous: 'previous',
     next: 'next',
     save: "Save",
     change: "Change",
     aboutUs: "About us",
     farms: 'Farms',
     cages: 'Cages',
     controllers: 'Controllers',
     chart: 'chart',
     messages: 'messages',
     otherFunctions: 'otherFunctions',
     menuMain: "Main",
     menuHome: "Home",
     menuProfile: "Profile",
     menuMoveMedia: "Move media",
     menuMoveBase: "Move base",
     menuUsers: "Users",
     menuGroups: "Groups",
     menuLogin: "Login",
     menuLogout: "Logout",

     password: 'password',
     signUp: "Sign up",
     dontHaveAcc: "Dont have account",
     firstName: "First Name",
     lastName: "LastName",
     alreadyHaveAcc: "Already have an account?",

     animation: "animation",
     language: "language",
     mainInfo: "Agriculture in Ukraine is one of the leading sectors of Ukraine's economy. In addition to the stable provision of the country's population with quality, safe, affordable food, Ukraine's agriculture is able to make a significant contribution to solving the world problem of hunger. Its production potential far exceeds the needs of the domestic market. In the structure of gross agricultural output, livestock accounts for more than 38%. In general, the tasks of animal husbandry are the production of high quality food and valuable raw materials for food and light industry. Thousands of small business structures live on livestock. These structures perform important economic functions and provide a wide range of services. In a specific direction, the system is designed for private enterprise, it can be small livestock and all its components. The purpose of the course work is to develop a software system for small livestock, which includes 4 parts: server part, web application, mobile application, smart device application. The software system should help increase the productivity of the economy, reduce efforts to manage it.",

     popular: "Popular",
     fresh: "Fresh",
     tags: "Tags"

 },
 ua: {
     specification: "Специфікація",
     idCage: "Клітка",

     monday: "Пн",
     tuesday: "Вт",
     wednesday: "Ср",
     thursday: "Чт",
     friday: "Пт",
     saturday: "Сб",
     sunday: "Нд",
     _id: 'id',
     contains: 'Наявно',
     add: 'Додати',
     select: 'Виділити',
     normal: 'Звичайний режим',
     deleteSelected: 'Видалити виділене',
     unselect: 'Відмінити виділення',
     locale: 'ua',
     registered: 'створено',
     name: 'назва',
     location: 'локація',
     animalKind: 'вид',

     capacity: 'кількість',
     idFarm: 'id господарства',


     change: "Змінити",
     previous: 'попередня',
     next: 'наступна',
     save: "Зберегти",
     cages: 'Клітки',
     controllers: 'Контролери',
     chart: 'Дані',
     messages: 'Повідлмлення',
     otherFunctions: 'Інші функції',
     farms: 'Господарства',
     aboutUs: "Про нас",
     mainInfo: "Сільське господарство України — одна з провідних галузей економіки України. Крім стабільного забезпечення населення країни якісним, безпечним, доступним продовольством, сільське господарство України спроможне на вагомий внесок у розв'язання світової проблеми голоду. Його потенціал виробництва значно перевищує потреби внутрішнього ринку. У структурі валової продукції сільського господарства, тваринництво становить понад 38 %. Загалом завдання тваринництва полягають у виробництві високоякісних продуктів харчування та цінної сировини для харчової та легкої промисловості. За рахунок тваринництва живуть тисячі малих структур підприємництва. Ці структури виконують важливі економічні функції та надають широкий спектр послуг. За конкретним спрямуванням система розрахована на приватне підприємництво господарства, це може бути дрібне тваринництво та всі його складові частини. Мета завдання курсової роботи розробити програмну систему для дрібного тваринництва, що включає 4 частини: серверну частину, веб-застосунок, мобільний застосунок, застосунок розумного пристрою. Програмна система повинна допомогти збільшити продуктивність господарства, зменшити зусилля щодо його ведення.",
     menuLogout: "Вийти",
     menuLogin: "Зайти",
     menuMain: "Головна",
     menuHome: "Домашня сторінка",
     menuProfile: "Профіль",
     menuMoveMedia: "Медіа руху",
     menuMoveBase: "Модулі руху",
     menuUsers: "Користувачі",
     menuGroups: "Групи",

     password: 'пароль',
     signUp: "Ввійти",
     dontHaveAcc: "Не маєте профілю",
     firstName: "Ім'я",
     lastName: "Прізвище",
     alreadyHaveAcc: "Вже маєте профіль?",

     animation: "Анімація",
     language: "Мова",

     popular: "Популярне",
     fresh: "Свіже",
     tags: "Теги"
 }
});

export default strings;